"""Initial schema

Revision ID: 62046de2ad8b
Revises: 
Create Date: 2025-10-27 15:18:47.736428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62046de2ad8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandates',
    sa.Column('mandate_id', sa.String(length=255), nullable=False),
    sa.Column('mandate_type', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('mandate_data', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mandate_id')
    )
    op.create_index(op.f('ix_mandates_session_id'), 'mandates', ['session_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_index(op.f('ix_cart_items_session_id'), 'cart_items', ['session_id'], unique=False)
    op.create_table('customer_inquiries',
    sa.Column('inquiry_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('inquiry_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_order_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_customer_inquiries_session_id'), 'customer_inquiries', ['session_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_mandate_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['payment_mandate_id'], ['mandates.mandate_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # op.add_column('catalog_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.alter_column('catalog_items', 'id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    # op.alter_column('catalog_items', 'name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=500),
    #            nullable=False)
    # op.alter_column('catalog_items', 'picture',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=1000),
    #            existing_nullable=True)
    # op.alter_column('catalog_items', 'product_image_url',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=1000),
    #            existing_nullable=True)
    # op.drop_index(op.f('idx_catalog_items_categories'), table_name='catalog_items')
    # op.drop_index(op.f('idx_catalog_items_image_embedding'), table_name='catalog_items', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.drop_index(op.f('idx_catalog_items_product_embedding'), table_name='catalog_items', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # op.drop_column('catalog_items', 'categories')
    # op.drop_column('catalog_items', 'price_usd_nanos')
    # op.drop_column('catalog_items', 'price_usd_currency_code')
    # op.drop_column('catalog_items', 'price_usd_units')
    # op.drop_column('catalog_items', 'embed_model')
    # op.drop_column('catalog_items', 'metadata')
    # op.drop_column('catalog_items', 'image_embed_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('image_embed_model', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('embed_model', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('price_usd_units', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('price_usd_currency_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('price_usd_nanos', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('categories', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_catalog_items_product_embedding'), 'catalog_items', ['product_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_catalog_items_image_embedding'), 'catalog_items', ['product_image_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_catalog_items_categories'), 'catalog_items', [sa.literal_column('lower(categories)')], unique=False)
    op.alter_column('catalog_items', 'product_image_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('catalog_items', 'picture',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('catalog_items', 'name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('catalog_items', 'id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('catalog_items', 'created_at')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_customer_inquiries_session_id'), table_name='customer_inquiries')
    op.drop_table('customer_inquiries')
    op.drop_index(op.f('ix_cart_items_session_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_mandates_session_id'), table_name='mandates')
    op.drop_table('mandates')
    # ### end Alembic commands ###
